export default {
  contacts: [],
  cart: [],
  sorted_contacts: [],
  user_token: localStorage.getItem('user-token') || '',
  login_status: '',
  select_options: [
    {
      name: "all",
      value: "all",
    },
    {
      name: "friends",
      value: "friends",
    },
    {
      name: "family",
      value: "family",
    },
    {
      name: "work",
      value: "work",
    },
  ],
  searchValue: "",
  selected_option: "all",
  are_options_visible: false,
  offline_data: {
    contacts: [
      {
        image: "1.jpg",
        name: "Michael",
        mobile: "+79650932200",
        article: "T1",
        available: true,
        category: "friends",
      },
      {
        image: "2.jpg",
        name: "Anna",
        mobile: "+79650933150",
        article: "T2",
        available: true,
        category: "friends",
      },
      {
        image: "3.jpg",
        name: "Yulia",
        mobile: "+79650932201",
        article: "T3",
        available: false,
        category: "family",
      },
      {
        image: "4.jpg",
        name: "Anton",
        mobile: "+79650932202",
        article: "T4",
        available: true,
        category: "family",
      },
      {
        image: "5.jpg",
        name: "Kristina",
        mobile: "+79650932203",
        article: "T5",
        available: false,
        category: "work",
      },
      {
        image: "6.jpg",
        name: "Tatyana",
        mobile: "+79650932204",
        article: "T6",
        available: true,
        category: "work",
      },
    ],
  },
};
